inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'spec/support/gravity_helper.rb'
    - 'spec/support/taxjar_helper.rb'
    - 'app/admin/**'
    - 'db/migrate/**'

Metrics/ParameterLists:
  Max: 9

Metrics/AbcSize:
  Max: 42
  Exclude:
    - "db/migrate/*"

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Metrics/ClassLength:
  Max: 190

Metrics/ModuleLength:
  Max: 151

Rails/ReversibleMigration:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/UselessComparison:
  Exclude:
    - "spec/lib/address_spec.rb"
