inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'spec/support/gravity_helper.rb'
    - 'spec/support/taxjar_helper.rb'
    - 'app/admin/**'

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/ReversibleMigration:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
