development: &default
  stripe_api_key: <%= ENV['STRIPE_API_KEY'] || '' %>
  webhook_secret: <%= ENV['STRIPE_WEBHOOK_SECRET'] || 'https://media.giphy.com/media/NdKVEei95yvIY/giphy.gif' %>
test:
  <<: *default
production:
  <<: *default