---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exchange-web
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exchange
        component: web
        layer: application
      name: exchange-web
    spec:
      containers:
      - name: exchange-web
        env:
        - name: RAILS_SERVE_STATIC_FILES
          value: 'true'
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: RAILS_ENV
          value: production
        envFrom:
        - configMapRef:
            name: exchange-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/exchange:production
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange
    component: web
    layer: application
  name: exchange-web
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: exchange
    component: web
    layer: application
  type: LoadBalancer
