---
version: '2'
services:
  exchange:
    extends:
      file: common.yml
      service: exchange
    ports:
    - 8080:8080
    environment:
    - RAILS_ENV=test
    - DATABASE_HOST=exchange-db
    - DATABASE_USER=postgres
    - REDIS_URL=redis://exchange-redis

    - CI_PULL_REQUEST=$CI_PULL_REQUEST
    - CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST
    - CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM
    - DANGER_GITHUB_API_TOKEN=$DANGER_GITHUB_API_TOKEN


    command: ./hokusai/ci.sh
    depends_on:
      - exchange-db
      - exchange-redis
  exchange-db:
    image: postgres:9.6-alpine
  exchange-redis:
    image: redis:3.2-alpine
